x-dagster-dags-service: &dagster-dags-service
  restart: no
  depends_on:
    - postgres
  env_file:
    - .postgres_env
  volumes:
    - dagster_dags_logs:/logs

services:
  dagster_dags:
    <<: *dagster-dags-service
    container_name: dagster_dags
    image: dagster-dags

  dagster_dags_dev:
    <<: *dagster-dags-service
    container_name: dagster_dags_dev
    image: dagster-dags-dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .postgres_env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dagster_dags_logs:
  postgres_data:
