x-dags-service: &dags-service
  restart: no
  depends_on:
    - postgres
  env_file:
    - .postgres_env
  volumes:
    - dags_logs:/logs

services:
  dags:
    <<: *dags-service
    container_name: dags
    image: dags

  dags_dev:
    <<: *dags-service
    container_name: dags_dev
    image: dags-dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .postgres_env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dags_logs:
  postgres_data:
