x-dagster-dags-service: &dagster-dags-service
  restart: no
  depends_on:
    - dagster_postgres
  ports:
    - "127.0.0.1:3000:3000"
  env_file:
    - .postgres_env
  volumes:
    - dagster_dags_logs:/logs
    - /mnt/dagster_io:/mnt/dagster_io
    - /var/run/docker.sock:/var/run/docker.sock

services:
  dagster_dags:
    <<: *dagster-dags-service
    container_name: dagster_dags
    image: dagster-dags

  dagster_daemon:
    <<: *dagster-dags-service
    container_name: dagster_daemon
    image: dagster-dags
    entrypoint:
      - dagster-daemon
      - run
    ports:
      - "127.0.0.1:3001:3000"

  dagster_dags_dev:
    <<: *dagster-dags-service
    container_name: dagster_dags_dev
    image: dagster-dags-dev

  dagster_postgres:
    image: postgres:16-alpine
    container_name: dagster_postgres
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - .postgres_env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dagster_dags_logs:
  postgres_data:

networks:
  default:
    name: main-network
